---
# tasks file for CentOS7-CIS
- name: Check OS version and family
  fail:
      msg: "This role can only be run agaist CentOS 7. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when:
      - ansible_os_family == 'CentOS'
      - ansible_distribution_major_version | version_compare('7', '!=')
  tags:
      - always

- name: Check ansible version
  fail:
      msg: You must use ansible 2.1 or greater
  when: not ansible_version.full | version_compare('2.1', '>=')
  tags:
      - always

- import_tasks: prelim.yml
  become: yes
  tags:
      - prelim_tasks
      - always

- import_tasks: section1.yml
  become: yes
  when: centos7cis_section1

- import_tasks: section2.yml
  become: yes
  when: centos7cis_section2

- import_tasks: section3.yml
  become: yes
  when: centos7cis_section3

- import_tasks: section4.yml
  become: yes
  when: centos7cis_section4

- import_tasks: section5.yml
  become: yes
  when: centos7cis_section5

- import_tasks: section6.yml
  become: yes
  when: centos7cis_section6

- import_tasks: post.yml
  become: yes
  tags:
      - post_tasks
      - always
